sudo: required
services:
  - docker

before_install: -docker build -t mgnkgn/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mgnkgn/react-test npm test

after_success:
  - docker build -t mgnkgn/multi-client ./client
  - docker build -t mgnkgn/multi-nginx ./nginx
  - docker build -t mgnkgn/multi-server ./server
  - docker build -t mgnkgn/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push mgnkgn/multi-client
  - docker push mgnkgn/multi-nginx
  - docker push mgnkgn/multi-server
  - docker push mgnkgn/multi-worker
